#!/usr/bin/env node

const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const dataDir = path.join(root, 'data');
const examsDir = path.join(dataDir, 'exams');
const readJSON = (filePath) => JSON.parse(fs.readFileSync(filePath, 'utf8'));

const registry = readJSON(path.join(dataDir, 'registry.json'));
const papers = {};
const answerKeys = {};

for (const entry of fs.readdirSync(examsDir, { withFileTypes: true })) {
  if (!entry.isDirectory()) continue;
  const examDir = path.join(examsDir, entry.name);
  const paperPath = path.join(examDir, 'paper.json');
  if (!fs.existsSync(paperPath)) continue;
  const paper = readJSON(paperPath);
  const paperId = paper.paper?.id || entry.name;
  papers[paperId] = paper;
  const answerPath = path.join(examDir, 'answer-key.json');
  if (fs.existsSync(answerPath)) answerKeys[paperId] = readJSON(answerPath);
}

const payload = { registry, papers, answerKeys };
const output = `// Generated by scripts/generate-demo.js. Do not edit by hand.\nwindow.__LAW_DEMO__ = ${JSON.stringify(payload, null, 2)};\n`;
fs.writeFileSync(path.join(dataDir, 'demo.js'), output);
console.log(`Generated data/demo.js for ${Object.keys(papers).length} exam package(s).`);
